site_name: ForagingFlipKit Documentation
repo_url: https://github.com/AttentionInActionLab/ForagingFlipKit
repo_name: ForagingFlipKit
theme:
  name: material
  logo: assets/logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - content.action.edit
  palette:
    - scheme: default
      primary: teal
      accent: indigo
nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - Config Entries: configentries.md
  - Experimental Design: design.md
  - Before a Patch: before_a_patch.md
  - Time Limits: timelimits.md
  - Audio: audio.md
