site_name: ForagingFlipKit
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.action.edit
  palette:
    - scheme: default
      primary: teal
      accent: indigo
nav:
  - Home: index.md
